
interface _GlobalComponents {
      'ButtonsButton': typeof import("../components/Buttons/Button.vue")['default']
    'ButtonsLangSwitcher': typeof import("../components/Buttons/LangSwitcher.vue")['default']
    'ButtonsPreloader': typeof import("../components/Buttons/Preloader.vue")['default']
    'LandingComponentsAboutBanner': typeof import("../components/LandingComponents/AboutBanner.vue")['default']
    'LandingComponentsAlgorithmInfo': typeof import("../components/LandingComponents/AlgorithmInfo.vue")['default']
    'LandingComponentsBookDemoBanner': typeof import("../components/LandingComponents/BookDemoBanner.vue")['default']
    'LandingComponentsFooter': typeof import("../components/LandingComponents/Footer.vue")['default']
    'LandingComponentsForWhom': typeof import("../components/LandingComponents/ForWhom.vue")['default']
    'LandingComponentsHeader': typeof import("../components/LandingComponents/Header.vue")['default']
    'LandingComponentsHowItWorks': typeof import("../components/LandingComponents/HowItWorks.vue")['default']
    'LandingComponentsScienceBehind': typeof import("../components/LandingComponents/ScienceBehind.vue")['default']
    'LandingComponentsStartBanner': typeof import("../components/LandingComponents/StartBanner.vue")['default']
    'LandingComponentsStatisticBanner': typeof import("../components/LandingComponents/StatisticBanner.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyButtonsButton': typeof import("../components/Buttons/Button.vue")['default']
    'LazyButtonsLangSwitcher': typeof import("../components/Buttons/LangSwitcher.vue")['default']
    'LazyButtonsPreloader': typeof import("../components/Buttons/Preloader.vue")['default']
    'LazyLandingComponentsAboutBanner': typeof import("../components/LandingComponents/AboutBanner.vue")['default']
    'LazyLandingComponentsAlgorithmInfo': typeof import("../components/LandingComponents/AlgorithmInfo.vue")['default']
    'LazyLandingComponentsBookDemoBanner': typeof import("../components/LandingComponents/BookDemoBanner.vue")['default']
    'LazyLandingComponentsFooter': typeof import("../components/LandingComponents/Footer.vue")['default']
    'LazyLandingComponentsForWhom': typeof import("../components/LandingComponents/ForWhom.vue")['default']
    'LazyLandingComponentsHeader': typeof import("../components/LandingComponents/Header.vue")['default']
    'LazyLandingComponentsHowItWorks': typeof import("../components/LandingComponents/HowItWorks.vue")['default']
    'LazyLandingComponentsScienceBehind': typeof import("../components/LandingComponents/ScienceBehind.vue")['default']
    'LazyLandingComponentsStartBanner': typeof import("../components/LandingComponents/StartBanner.vue")['default']
    'LazyLandingComponentsStatisticBanner': typeof import("../components/LandingComponents/StatisticBanner.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const ButtonsButton: typeof import("../components/Buttons/Button.vue")['default']
export const ButtonsLangSwitcher: typeof import("../components/Buttons/LangSwitcher.vue")['default']
export const ButtonsPreloader: typeof import("../components/Buttons/Preloader.vue")['default']
export const LandingComponentsAboutBanner: typeof import("../components/LandingComponents/AboutBanner.vue")['default']
export const LandingComponentsAlgorithmInfo: typeof import("../components/LandingComponents/AlgorithmInfo.vue")['default']
export const LandingComponentsBookDemoBanner: typeof import("../components/LandingComponents/BookDemoBanner.vue")['default']
export const LandingComponentsFooter: typeof import("../components/LandingComponents/Footer.vue")['default']
export const LandingComponentsForWhom: typeof import("../components/LandingComponents/ForWhom.vue")['default']
export const LandingComponentsHeader: typeof import("../components/LandingComponents/Header.vue")['default']
export const LandingComponentsHowItWorks: typeof import("../components/LandingComponents/HowItWorks.vue")['default']
export const LandingComponentsScienceBehind: typeof import("../components/LandingComponents/ScienceBehind.vue")['default']
export const LandingComponentsStartBanner: typeof import("../components/LandingComponents/StartBanner.vue")['default']
export const LandingComponentsStatisticBanner: typeof import("../components/LandingComponents/StatisticBanner.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyButtonsButton: typeof import("../components/Buttons/Button.vue")['default']
export const LazyButtonsLangSwitcher: typeof import("../components/Buttons/LangSwitcher.vue")['default']
export const LazyButtonsPreloader: typeof import("../components/Buttons/Preloader.vue")['default']
export const LazyLandingComponentsAboutBanner: typeof import("../components/LandingComponents/AboutBanner.vue")['default']
export const LazyLandingComponentsAlgorithmInfo: typeof import("../components/LandingComponents/AlgorithmInfo.vue")['default']
export const LazyLandingComponentsBookDemoBanner: typeof import("../components/LandingComponents/BookDemoBanner.vue")['default']
export const LazyLandingComponentsFooter: typeof import("../components/LandingComponents/Footer.vue")['default']
export const LazyLandingComponentsForWhom: typeof import("../components/LandingComponents/ForWhom.vue")['default']
export const LazyLandingComponentsHeader: typeof import("../components/LandingComponents/Header.vue")['default']
export const LazyLandingComponentsHowItWorks: typeof import("../components/LandingComponents/HowItWorks.vue")['default']
export const LazyLandingComponentsScienceBehind: typeof import("../components/LandingComponents/ScienceBehind.vue")['default']
export const LazyLandingComponentsStartBanner: typeof import("../components/LandingComponents/StartBanner.vue")['default']
export const LazyLandingComponentsStatisticBanner: typeof import("../components/LandingComponents/StatisticBanner.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
