// Generated by nuxi
/// <reference types="@nuxtjs/i18n" />
/// <reference types="@nuxtjs/sitemap" />
/// <reference types="@nuxtjs/robots" />
/// <reference types="@nuxtjs/seo" />
/// <reference types="@nuxt/devtools" />
/// <reference types="@nuxt/telemetry" />
/// <reference types="nuxt" />
/// <reference path="types/plugins.d.ts" />
/// <reference path="types/schema.d.ts" />
/// <reference path="types/app.config.d.ts" />
/// <reference types="vite/client" />
/// <reference path="types/i18n-plugin.d.ts" />
/// <reference path="module/nuxt-site-config.d.ts" />
/// <reference path="module/nuxt-sitemap.d.ts" />
/// <reference path="module/nuxt-robots.d.ts" />
/// <reference path="vue-router-stub.d.ts" />
/// <reference types="vue-router" />
/// <reference path="types/middleware.d.ts" />
/// <reference path="types/layouts.d.ts" />
/// <reference path="components.d.ts" />
/// <reference path="imports.d.ts" />
/// <reference path="types/imports.d.ts" />
/// <reference path="schema/nuxt.schema.d.ts" />
/// <reference path="types/nitro.d.ts" />

export {}
